runtime: python39

entrypoint: gunicorn -b :$PORT app:app

# Optional: If you want to specify the instance class
instance_class: F2

# Optional: If you want to specify environment variables
env_variables:
  FLASK_ENV: 'production'
