apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-app
spec:
  template:
    spec:
      containers:
        - image: gcr.io/[PROJECT-ID]/flask-app
          ports:
            - containerPort: 8080
